"""initial schema — jobs / job_actions / application_notes (Phase D)

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-17

Hand-written (not autogenerated) so the first migration is reviewable and exactly matches
the split-schema decision: ad data (jobs) and human edits (job_actions / application_notes)
live in separate tables with opposite lifecycles. Indexes: jobs.posted_date (freshness
window) and job_actions.status (dashboard 'touched' filter).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), primary_key=True),
        sa.Column("source", postgresql.ARRAY(sa.Text())),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("location", sa.Text()),
        sa.Column("alt_locations", postgresql.ARRAY(sa.Text())),
        sa.Column("remote", sa.Boolean()),
        sa.Column("url", sa.Text()),
        sa.Column("ats_url", sa.Text()),
        sa.Column("description", sa.Text()),
        sa.Column("posted_date", sa.Text()),
        sa.Column("posted_ts", sa.BigInteger()),
        sa.Column("triage_verdict", sa.Text()),
        sa.Column("triage_reason", sa.Text()),
        sa.Column("triaged_date", sa.Text()),
        sa.Column("skip_reason", sa.Text()),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_jobs_posted_date", "jobs", ["posted_date"])

    op.create_table(
        "job_actions",
        sa.Column("job_id", sa.String(length=32), sa.ForeignKey("jobs.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("status", sa.Text(), nullable=False, server_default="new"),
        sa.Column("notes", sa.Text()),
        sa.Column("applied_date", sa.Date()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_job_actions_status", "job_actions", ["status"])

    op.create_table(
        "application_notes",
        sa.Column("job_id", sa.String(length=32), sa.ForeignKey("jobs.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("notes", sa.Text()),
        sa.Column("salary", sa.Text()),
        sa.Column("links", postgresql.ARRAY(sa.Text())),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("application_notes")
    op.drop_index("ix_job_actions_status", table_name="job_actions")
    op.drop_table("job_actions")
    op.drop_index("ix_jobs_posted_date", table_name="jobs")
    op.drop_table("jobs")
